apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcontent-deployment
spec:
  replicas: 3
  minReadySeconds: 5
  selector:
    matchLabels:
      app: gcontent
  template:
    metadata:
      labels:
        app: gcontent
    spec:
      containers:
      - name: my-container
        image: chyld/content:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: LoadBalancer
  selector:
    app: gcontent
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 80

